# Generated by Django 5.0.1 on 2024-01-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='guestCanPause',
            new_name='guest_can_pause',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='uniqueCode',
            new_name='unique_code',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='voteToSkip',
            new_name='vote_to_skip',
        ),
    ]
