# Generated by Django 5.0.1 on 2024-01-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_createdat_room_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='vote_to_skip',
            new_name='votes_to_skip',
        ),
    ]
