# Generated by Django 5.0.1 on 2024-01-28 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_unique_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='unique_code',
            new_name='code',
        ),
    ]
