# Generated by Django 5.0.1 on 2024-01-28 23:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_unique_code_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.generateUniqueCode, max_length=6, unique=True),
        ),
    ]
